# Generated by Django 4.2.16 on 2025-04-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("age", models.IntegerField()),
                ("emailid", models.EmailField(max_length=254)),
                ("marks", models.IntegerField()),
                ("phno", models.IntegerField()),
            ],
        ),
    ]
